            - name: Codecov
  # You may pin to the exact commit or the version.
  # uses: codecov/codecov-action@e0b68c6749509c5f83f984dd99a76a1c1a231044
  uses: codecov/codecov-action@v4.0.1
  with:
    # Repository upload token - get it from codecov.io. Required only for private repositories
    token: # optional
    # Specify the path to the Codecov YML
    codecov_yml_path: # optional
    # Override to specify the parent commit SHA
    commit_parent: # optional
    # Directory to search for coverage reports.
    directory: # optional
    # Disable search for coverage files. This is helpful when specifying what files you want to upload with the --file option.
    disable_search: # optional
    # Disable file fixes to ignore common lines from coverage (e.g. blank lines or empty brackets)
    disable_file_fixes: # optional
    # Don't upload files to Codecov
    dry_run: # optional
    # Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
    env_vars: # optional
    # Folders to exclude from search
    exclude: # optional
    # Specify whether or not CI build should fail if Codecov runs into an error during upload
    fail_ci_if_error: # optional
    # Path to coverage file to upload
    file: # optional
    # Comma-separated list of files to upload
    files: # optional
    # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
    flags: # optional
    # Raise no exceptions when no coverage reports found
    handle_no_reports_found: # optional
    # The job code
    job_code: # optional
    # User defined upload name. Visible in Codecov UI
    name: # optional
    # Override the assumed OS. Options are linux | macos | windows.
    os: # optional
    # Specify the branch name
    override_branch: # optional
    # Specify the build number
    override_build: # optional
    # The URL of the build where this is running
    override_build_url: # optional
    # Specify the commit SHA
    override_commit: # optional
    # Specify the pull request number
    override_pr: # optional
    # plugins to run. Options: xcode, gcov, pycoverage. The default behavior runs them all.
    plugin: # optional
    # Comma-separated list of plugins for use during upload.
    plugins: # optional
    # The code of the report. If unsure, do not include
    report_code: # optional
    # Used when not in git/hg project to identify project root directory
    root_dir: # optional
    # Specify the slug manually (Enterprise use)
    slug: # optional
    # Specify the base url to upload (Enterprise use)
    url: # optional
    # Use the legacy upload endpoint
    use_legacy_upload_endpoint: # optional
    # Specify whether the Codecov output should be verbose
    verbose: # optional
    # Specify which version of the Codecov CLI should be used. Defaults to `latest`
    version: # optional
    # Directory in which to execute codecov.sh
    working-directory: # optional
          
